// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportModbusConfig() {
  return window['go']['main']['App']['ExportModbusConfig']();
}

export function GetModbusConfig() {
  return window['go']['main']['App']['GetModbusConfig']();
}

export function GetValue() {
  return window['go']['main']['App']['GetValue']();
}

export function ImportModbusConfig() {
  return window['go']['main']['App']['ImportModbusConfig']();
}

export function RemoveModbusConfig(arg1) {
  return window['go']['main']['App']['RemoveModbusConfig'](arg1);
}

export function SetModbusConfig(arg1) {
  return window['go']['main']['App']['SetModbusConfig'](arg1);
}

export function SetValue(arg1, arg2) {
  return window['go']['main']['App']['SetValue'](arg1, arg2);
}

export function StartModbusServer(arg1) {
  return window['go']['main']['App']['StartModbusServer'](arg1);
}

export function StopModbusServer() {
  return window['go']['main']['App']['StopModbusServer']();
}
